import Link from "next/link";

export const metadata = {
  title: 'AI Finance Insight Radar',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // 机构级设计 Token
  const colors = {
    bgNav: "#ffffff",
    textPrimary: "#0f172a",
    textSecondary: "#475569",
    accentBlue: "#004b87",
    border: "#e2e8f0"
  };

  const fonts = {
    serif: "Georgia, 'Times New Roman', Times, serif",
    sans: "Arial, 'Helvetica Neue', Helvetica, sans-serif"
  };

  return (
    <html lang="en">
      <body style={{ margin: 0, padding: 0, backgroundColor: "#f8f9fa", fontFamily: fonts.sans }}>
        {/* 全局顶部导航栏 (Corporate Top Navigation) */}
        <nav style={{ 
          display: "flex", 
          justifyContent: "space-between", 
          alignItems: "center", 
          padding: "16px 48px", 
          backgroundColor: colors.bgNav, 
          borderBottom: `1px solid ${colors.border}`,
          position: "sticky",
          top: 0,
          zIndex: 100
        }}>
          <div style={{ display: "flex", gap: "40px", alignItems: "center" }}>
            <div style={{ textDecoration: "none", color: colors.textPrimary, fontWeight: "bold", fontSize: "18px", fontFamily: fonts.serif }}>
              <span style={{ color: colors.accentBlue, marginRight: "6px" }}>■</span> 
              Insight Radar
            </div>
            
            <div style={{ display: "flex", gap: "28px" }}>
              <Link href="/posts" style={{ textDecoration: "none", color: colors.textSecondary, fontSize: "14px", fontWeight: "bold", letterSpacing: "0.5px" }}>
                Insight Terminal
              </Link>
              <Link href="/prompts" style={{ textDecoration: "none", color: colors.textSecondary, fontSize: "14px", fontWeight: "bold", letterSpacing: "0.5px" }}>
                Prompt Registry
              </Link>
              <Link href="/progress-report" style={{ textDecoration: "none", color: colors.textSecondary, fontSize: "14px", fontWeight: "bold", letterSpacing: "0.5px" }}>
                Progress Report
              </Link>
            </div>
          </div>
          <div style={{ fontSize: "11px", color: colors.accentBlue, textTransform: "uppercase", letterSpacing: "1.5px", fontWeight: "bold", background: "rgba(0, 75, 135, 0.05)", padding: "4px 8px", border: `1px solid rgba(0, 75, 135, 0.2)` }}>
            Internal Prototype
          </div>
        </nav>

        {children}
      </body>
    </html>
  )
}