import { Metadata } from 'next';
import TopNav from './TopNav';

export const metadata: Metadata = {
  title: 'AI Finance Insight Radar',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const colors = { bgNav: "#ffffff", textPrimary: "#0f172a", accentBlue: "#004b87", border: "#e2e8f0" };
  const fonts = { serif: "Georgia, 'Times New Roman', Times, serif", sans: "Arial, 'Helvetica Neue', Helvetica, sans-serif" };

  return (
    <html lang="en">
      <body style={{ margin: 0, padding: 0, backgroundColor: "#f8f9fa", fontFamily: fonts.sans }}>
        <nav style={{ 
          display: "flex", 
          justifyContent: "space-between", 
          alignItems: "center", 
          padding: "0 48px", // 🌟 关键：去掉上下 padding
          height: "64px",    // 🌟 关键：改用固定高度撑起导航栏
          backgroundColor: colors.bgNav, 
          borderBottom: `1px solid ${colors.border}`,
          position: "sticky",
          top: 0,
          zIndex: 100
        }}>
          <div style={{ display: "flex", gap: "48px", alignItems: "center", height: "100%" }}>
            <div style={{ textDecoration: "none", color: colors.textPrimary, fontWeight: "bold", fontSize: "18px", fontFamily: fonts.serif }}>
              <span style={{ color: colors.accentBlue, marginRight: "6px" }}>■</span> 
              Insight Radar
            </div>
            {/* 动态高亮导航 */}
            <TopNav />
          </div>
          <div style={{ fontSize: "11px", color: colors.accentBlue, textTransform: "uppercase", letterSpacing: "1.5px", fontWeight: "bold", background: "rgba(0, 75, 135, 0.05)", padding: "4px 8px", border: `1px solid rgba(0, 75, 135, 0.2)` }}>
            Internal Prototype
          </div>
        </nav>
        {children}
      </body>
    </html>
  )
}